/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as FacilitatorsRouteImport } from './routes/facilitators'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as BagsIndexRouteImport } from './routes/bags/index'
import { Route as BagsSlugRouteImport } from './routes/bags/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorsRoute = FacilitatorsRouteImport.update({
  id: '/facilitators',
  path: '/facilitators',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsIndexRoute = BagsIndexRouteImport.update({
  id: '/bags/',
  path: '/bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsSlugRoute = BagsSlugRouteImport.update({
  id: '/bags/$slug',
  path: '/bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/facilitators': typeof FacilitatorsRoute
  '/methodology': typeof MethodologyRoute
  '/schools': typeof SchoolsRoute
  '/bags/$slug': typeof BagsSlugRoute
  '/bags/': typeof BagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/facilitators': typeof FacilitatorsRoute
  '/methodology': typeof MethodologyRoute
  '/schools': typeof SchoolsRoute
  '/bags/$slug': typeof BagsSlugRoute
  '/bags': typeof BagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/facilitators': typeof FacilitatorsRoute
  '/methodology': typeof MethodologyRoute
  '/schools': typeof SchoolsRoute
  '/bags/$slug': typeof BagsSlugRoute
  '/bags/': typeof BagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/facilitators'
    | '/methodology'
    | '/schools'
    | '/bags/$slug'
    | '/bags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/facilitators'
    | '/methodology'
    | '/schools'
    | '/bags/$slug'
    | '/bags'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/facilitators'
    | '/methodology'
    | '/schools'
    | '/bags/$slug'
    | '/bags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  FacilitatorsRoute: typeof FacilitatorsRoute
  MethodologyRoute: typeof MethodologyRoute
  SchoolsRoute: typeof SchoolsRoute
  BagsSlugRoute: typeof BagsSlugRoute
  BagsIndexRoute: typeof BagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitators': {
      id: '/facilitators'
      path: '/facilitators'
      fullPath: '/facilitators'
      preLoaderRoute: typeof FacilitatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/': {
      id: '/bags/'
      path: '/bags'
      fullPath: '/bags/'
      preLoaderRoute: typeof BagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/$slug': {
      id: '/bags/$slug'
      path: '/bags/$slug'
      fullPath: '/bags/$slug'
      preLoaderRoute: typeof BagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  FacilitatorsRoute: FacilitatorsRoute,
  MethodologyRoute: MethodologyRoute,
  SchoolsRoute: SchoolsRoute,
  BagsSlugRoute: BagsSlugRoute,
  BagsIndexRoute: BagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
