/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as Q360RouteImport } from './routes/q360'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoreRouteImport } from './routes/store'
import { Route as WalkingQuranRouteImport } from './routes/walking-quran'
import { Route as BagsIndexRouteImport } from './routes/bags/index'
import { Route as BagsSlugRouteImport } from './routes/bags/$slug'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as FacilitatorsIndexRouteImport } from './routes/facilitators/index'
import { Route as FacilitatorsApplyRouteImport } from './routes/facilitators/apply'
import { Route as SchoolsDashboardRouteImport } from './routes/schools.dashboard'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyNumberRouteImport } from './routes/verify.$number'
import { Route as Q360AssessBagSlugRouteImport } from './routes/q360.assess.$bagSlug'
import { Route as Q360InviteTokenRouteImport } from './routes/q360.invite.$token'
import { Route as Q360RateAssessmentIdRouteImport } from './routes/q360.rate.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const Q360Route = Q360RouteImport.update({
  id: '/q360',
  path: '/q360',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkingQuranRoute = WalkingQuranRouteImport.update({
  id: '/walking-quran',
  path: '/walking-quran',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsIndexRoute = BagsIndexRouteImport.update({
  id: '/bags/',
  path: '/bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsSlugRoute = BagsSlugRouteImport.update({
  id: '/bags/$slug',
  path: '/bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorsIndexRoute = FacilitatorsIndexRouteImport.update({
  id: '/facilitators/',
  path: '/facilitators/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorsApplyRoute = FacilitatorsApplyRouteImport.update({
  id: '/facilitators/apply',
  path: '/facilitators/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsDashboardRoute = SchoolsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SchoolsRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyNumberRoute = VerifyNumberRouteImport.update({
  id: '/verify/$number',
  path: '/verify/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const Q360AssessBagSlugRoute = Q360AssessBagSlugRouteImport.update({
  id: '/assess/$bagSlug',
  path: '/assess/$bagSlug',
  getParentRoute: () => Q360Route,
} as any)
const Q360InviteTokenRoute = Q360InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => Q360Route,
} as any)
const Q360RateAssessmentIdRoute = Q360RateAssessmentIdRouteImport.update({
  id: '/rate/$assessmentId',
  path: '/rate/$assessmentId',
  getParentRoute: () => Q360Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/methodology': typeof MethodologyRoute
  '/q360': typeof Q360RouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/walking-quran': typeof WalkingQuranRoute
  '/bags/$slug': typeof BagsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/facilitators/apply': typeof FacilitatorsApplyRoute
  '/schools/dashboard': typeof SchoolsDashboardRoute
  '/verify/$number': typeof VerifyNumberRoute
  '/bags/': typeof BagsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/facilitators/': typeof FacilitatorsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/q360/assess/$bagSlug': typeof Q360AssessBagSlugRoute
  '/q360/invite/$token': typeof Q360InviteTokenRoute
  '/q360/rate/$assessmentId': typeof Q360RateAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/methodology': typeof MethodologyRoute
  '/q360': typeof Q360RouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/walking-quran': typeof WalkingQuranRoute
  '/bags/$slug': typeof BagsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/facilitators/apply': typeof FacilitatorsApplyRoute
  '/schools/dashboard': typeof SchoolsDashboardRoute
  '/verify/$number': typeof VerifyNumberRoute
  '/bags': typeof BagsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/facilitators': typeof FacilitatorsIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/q360/assess/$bagSlug': typeof Q360AssessBagSlugRoute
  '/q360/invite/$token': typeof Q360InviteTokenRoute
  '/q360/rate/$assessmentId': typeof Q360RateAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/methodology': typeof MethodologyRoute
  '/q360': typeof Q360RouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/walking-quran': typeof WalkingQuranRoute
  '/bags/$slug': typeof BagsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/facilitators/apply': typeof FacilitatorsApplyRoute
  '/schools/dashboard': typeof SchoolsDashboardRoute
  '/verify/$number': typeof VerifyNumberRoute
  '/bags/': typeof BagsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/facilitators/': typeof FacilitatorsIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/q360/assess/$bagSlug': typeof Q360AssessBagSlugRoute
  '/q360/invite/$token': typeof Q360InviteTokenRoute
  '/q360/rate/$assessmentId': typeof Q360RateAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/impact'
    | '/methodology'
    | '/q360'
    | '/schools'
    | '/sitemap.xml'
    | '/store'
    | '/walking-quran'
    | '/bags/$slug'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/facilitators/apply'
    | '/schools/dashboard'
    | '/verify/$number'
    | '/bags/'
    | '/blog/'
    | '/facilitators/'
    | '/verify/'
    | '/q360/assess/$bagSlug'
    | '/q360/invite/$token'
    | '/q360/rate/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/impact'
    | '/methodology'
    | '/q360'
    | '/schools'
    | '/sitemap.xml'
    | '/store'
    | '/walking-quran'
    | '/bags/$slug'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/facilitators/apply'
    | '/schools/dashboard'
    | '/verify/$number'
    | '/bags'
    | '/blog'
    | '/facilitators'
    | '/verify'
    | '/q360/assess/$bagSlug'
    | '/q360/invite/$token'
    | '/q360/rate/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/impact'
    | '/methodology'
    | '/q360'
    | '/schools'
    | '/sitemap.xml'
    | '/store'
    | '/walking-quran'
    | '/bags/$slug'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/facilitators/apply'
    | '/schools/dashboard'
    | '/verify/$number'
    | '/bags/'
    | '/blog/'
    | '/facilitators/'
    | '/verify/'
    | '/q360/assess/$bagSlug'
    | '/q360/invite/$token'
    | '/q360/rate/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  MethodologyRoute: typeof MethodologyRoute
  Q360Route: typeof Q360RouteWithChildren
  SchoolsRoute: typeof SchoolsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  WalkingQuranRoute: typeof WalkingQuranRoute
  BagsSlugRoute: typeof BagsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  FacilitatorsApplyRoute: typeof FacilitatorsApplyRoute
  VerifyNumberRoute: typeof VerifyNumberRoute
  BagsIndexRoute: typeof BagsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FacilitatorsIndexRoute: typeof FacilitatorsIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q360': {
      id: '/q360'
      path: '/q360'
      fullPath: '/q360'
      preLoaderRoute: typeof Q360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walking-quran': {
      id: '/walking-quran'
      path: '/walking-quran'
      fullPath: '/walking-quran'
      preLoaderRoute: typeof WalkingQuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/': {
      id: '/bags/'
      path: '/bags'
      fullPath: '/bags/'
      preLoaderRoute: typeof BagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/$slug': {
      id: '/bags/$slug'
      path: '/bags/$slug'
      fullPath: '/bags/$slug'
      preLoaderRoute: typeof BagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitators/': {
      id: '/facilitators/'
      path: '/facilitators'
      fullPath: '/facilitators/'
      preLoaderRoute: typeof FacilitatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitators/apply': {
      id: '/facilitators/apply'
      path: '/facilitators/apply'
      fullPath: '/facilitators/apply'
      preLoaderRoute: typeof FacilitatorsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/dashboard': {
      id: '/schools/dashboard'
      path: '/dashboard'
      fullPath: '/schools/dashboard'
      preLoaderRoute: typeof SchoolsDashboardRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$number': {
      id: '/verify/$number'
      path: '/verify/$number'
      fullPath: '/verify/$number'
      preLoaderRoute: typeof VerifyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q360/assess/$bagSlug': {
      id: '/q360/assess/$bagSlug'
      path: '/assess/$bagSlug'
      fullPath: '/q360/assess/$bagSlug'
      preLoaderRoute: typeof Q360AssessBagSlugRouteImport
      parentRoute: typeof Q360Route
    }
    '/q360/invite/$token': {
      id: '/q360/invite/$token'
      path: '/invite/$token'
      fullPath: '/q360/invite/$token'
      preLoaderRoute: typeof Q360InviteTokenRouteImport
      parentRoute: typeof Q360Route
    }
    '/q360/rate/$assessmentId': {
      id: '/q360/rate/$assessmentId'
      path: '/rate/$assessmentId'
      fullPath: '/q360/rate/$assessmentId'
      preLoaderRoute: typeof Q360RateAssessmentIdRouteImport
      parentRoute: typeof Q360Route
    }
  }
}

interface Q360RouteChildren {
  Q360AssessBagSlugRoute: typeof Q360AssessBagSlugRoute
  Q360InviteTokenRoute: typeof Q360InviteTokenRoute
  Q360RateAssessmentIdRoute: typeof Q360RateAssessmentIdRoute
}

const Q360RouteChildren: Q360RouteChildren = {
  Q360AssessBagSlugRoute: Q360AssessBagSlugRoute,
  Q360InviteTokenRoute: Q360InviteTokenRoute,
  Q360RateAssessmentIdRoute: Q360RateAssessmentIdRoute,
}

const Q360RouteWithChildren = Q360Route._addFileChildren(Q360RouteChildren)

interface SchoolsRouteChildren {
  SchoolsDashboardRoute: typeof SchoolsDashboardRoute
}

const SchoolsRouteChildren: SchoolsRouteChildren = {
  SchoolsDashboardRoute: SchoolsDashboardRoute,
}

const SchoolsRouteWithChildren =
  SchoolsRoute._addFileChildren(SchoolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  MethodologyRoute: MethodologyRoute,
  Q360Route: Q360RouteWithChildren,
  SchoolsRoute: SchoolsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  WalkingQuranRoute: WalkingQuranRoute,
  BagsSlugRoute: BagsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  FacilitatorsApplyRoute: FacilitatorsApplyRoute,
  VerifyNumberRoute: VerifyNumberRoute,
  BagsIndexRoute: BagsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  FacilitatorsIndexRoute: FacilitatorsIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
